# Generated by Django 5.0.4 on 2024-06-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_remove_priority_priority_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
